#!/usr/bin/env php
<?php
error_reporting(E_ALL | E_STRICT);
ini_set('display_errors', 1);
date_default_timezone_set('Europe/Oslo');

/**
 * Various Configuration Settings
 */
$version    = '1.0.2';
$vendorDir  = __DIR__ . '/../vendor';
$distDir    = __DIR__ . '/../build/dist';
$tmpDistDir = $distDir . '/tmp'; // Files will be placed here temporarly so we can zip/tar them.
$distFile   = $distDir . '/mcash-magento-'.$version; // Without extension

require_once $vendorDir . '/autoload.php';

$filesystem = new \Symfony\Component\Filesystem\Filesystem();
$filesystem->mirror('app/', sprintf('%s/app/', $tmpDistDir));
$filesystem->mirror('skin/', sprintf('%s/skin/', $tmpDistDir));
$filesystem->copy('LICENSE.md', sprintf('%s/app/code/community/Trollweb/Mcash/LICENSE.md', $tmpDistDir));

// All required files are in the temp. distribution directory

/**
 * Need to create the package.xml file required by Magento
 */
$xml = simplexml_load_string('<package/>');
$xml->addChild('name', 'mcash_magento');
$xml->addChild('version', $version);
$xml->addChild('stability', 'stable');
$xml->addChild('license', 'MIT')
    ->addAttribute('uri', 'https://github.com/mcash/mcash-magento/blob/master/LICENSE.md');
$xml->addChild('channel', 'community');
$xml->addChild('extends');
$xml->addChild('summary');
$xml->addChild('description');
$xml->addChild('notes');

$authorsNode = $xml->addChild('authors');

$authors = array(
    array(
        'Integrations Team', // Name
        'NotAvailableYet', // Magento Connect Username
        'help@mcash.no', // Email
    ),
);

foreach ($authors as $author) {
    $authorNode = $authorsNode->addChild('author');
    $authorNode->addChild('name', $author[0]);
    $authorNode->addChild('user', $author[1]);
    $authorNode->addChild('email', $author[2]);
}

$xml->addChild('date', date('Y-m-d'));
$xml->addChild('time', date('G:i:s'));
$xml->addChild('compatible');
$xml->addChild('dependencies');

$requiredNode = $xml->addChild('required', 'php');
$requiredNode->addAttribute('php_min', '5.4.0');
$requiredNode->addAttribute('php_max', '6.0.0');

$extensionsNode = $xml->addChild('extensions');

foreach (array('openssl', 'mcrypt') as $ext) {
    $extNode = $extensionsNode->addChild('name', $ext);
    $extNode->addChild('min');
    $extNode->addChild('max');
}

$targetNode = $xml->addChild('contents')->addChild('target');
$targetNode->addAttribute('name', 'mage');

$finder = new \Symfony\Component\Finder\Finder();
$finder
    ->files()
    ->in($tmpDistDir);

foreach ($finder as $file) {
    $node        = $targetNode;
    $directories = explode('/', $file->getRelativePathname());
    $filename    = array_pop($directories);

    for ($i = 1; $i <= count($directories); $i++) {
        $dir   = $directories[$i - 1];
        $nodes = $node->xpath('dir[@name="' . $dir . '"]');
        if (count($nodes)) {
            $node = array_pop($nodes);
        } else {
            $node = $node->addChild('dir');
            $node->addAttribute('name', $dir);
        }
    }

    $fileNode = $node->addChild('file');
    $fileNode->addAttribute('name', $file->getBaseName());
    $fileNode->addAttribute('hash', md5_file($file->getRealPath()));
}

$xml->asXml($tmpDistDir . '/package.xml');

// package.xml created, just need to tar/zip everything
$filesystem->remove($distFile.'.zip');
$filesystem->remove($distFile.'.tgz');

$process = new \Symfony\Component\Process\Process(
    sprintf('cd %s; tar -czf %s *', $tmpDistDir, $distFile.'.tgz')
);

$process->run();

// Cleanup
$filesystem->remove($tmpDistDir);
