<tr id="row_payment_mcash_regen_keys">
	<td class="label">
		<label for="mcash_regen_keys">Regenerer nøkkel</label>
	</td>
	<td class="value">
		<button id="mcash_regen_keys" title="Generer ny nøkkel" type="button" class="scalable save" ><span><span><span>Generer ny nøkkel</span></span></span></button>
	</td>
</tr>
<script>

	document.getElementById('mcash_regen_keys').onclick = function(e){
		new Ajax.Request(
			'<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/generatekey/generate"); ?>', 
			{
				onSuccess: function(transport){ 
					var response = transport.responseText.evalJSON(); 
					if( response.pubkey ){
						document.getElementById('mcash_pub_key').innerHTML = response.pubkey;
						alert('Ny nøkkel opprettet');	
					} else {
						alert('Noe gikk galt, vennligst prøv igjen');
					}
				},
				onError : function(err){
					alert('Noe gikk galt, vennligst prøv igjen');
					console.log(err);					
				}
			}
		);		
	}

</script>