<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <?php $_qrCodeImage = $this->getQrImage(); ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li class="mcash-qr <?php echo $this->isScanned() ? "hide" : "" ?>"><img src="<?php echo $_qrCodeImage; ?>"></li>
        <li class="mcash-qr <?php echo $this->isScanned() ? "hide" : "" ?>"><?php echo $this->__("Scan the mCASH QR code before you submit your order") ?></li>
        <li id="mcash-qr-scanned" class="<?php echo $this->isScanned() ? "" : "hide" ?>">
            <p class="scan-success"><?php echo $this->__("QR code is scanned.") ?></p>
            <p class="scan-info"><?php echo $this->__("Submit your order and accept the payment with the mCASH app on your phone to complete the order") ?></p>
        </li>
    </ul>


</fieldset>
