<div data-mcash-qr-image-url="<?php echo $this->getUrl("mcash/checkout/qr", array("_secure" => true)) ?>"></div>
<div data-mcash-status-url="<?php echo $this->getUrl("mcash/checkout/status", array("_secure" => true)) ?>"></div>
<div data-mcash-request-permissions-url="<?php echo $this->getUrl("mcash/checkout/requestPermissions", array("_secure" => true)) ?>"></div>
<div data-mcash-userinfo-url="<?php echo $this->getUrl("mcash/checkout/userinfo", array("_secure" => true)) ?>"></div>
